### ISSUE TITLE
plotGSEA with max.overlap parameter

### ISSUE THREAD

**Issue by loganylchen** [GangLiLab/genekitr#10]
Hi there,

Thanks for developing this fantasy package. I have tried this package a lot, and I want to raise an issue about the visualization of the GSEA results.

In the 'classic' mode, if the genes are overlapped, they will only show part of the genes. May I ask if you could add a "max.overlap" to customize the number of showing in the GSEA plot.

Best,
Logan

**Comment by reedliu** [comment]
Hi Logan,
Thanks for your feedback. 
Could you please give me the testing code so I can reproduce your result?

**Comment by loganylchen** [comment]
Sure, here are my codes
```
kk_easy<-readRDS('test.rds')

pathways <- c("Chemokine signaling pathway", "Fatty acid beta-oxidation")
genes <- c("CCR2", "CCL5", "CCL3", "VAV1", "SLC25A20", "PNPLA2", "CPT1A", "ACAT1", "ACSL5", "ECHS1", "ACADS", "ECI1", "ACADVL", "GCDH", "FABP5" , "CD36" , "FABP4" )
g <- plotGSEA(kk_easy, plot_type = "classic", show_pathway = pathways, show_gene = genes)
```

Then it will plot the figure as below:
![2023-04-11_12-07](https://user-images.githubusercontent.com/25150929/231053837-f18dba13-d8db-4ae0-90c7-1d2f3a3b2cfe.png)

Test data were attached below: [test.zip](https://github.com/GangLiLab/genekitr/files/11196418/test.zip)
