### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by maartenciers** [GangLiLab/genekitr#11]
How do we cite your tool? I can't find it? Thanks

**Comment by reedliu** [comment]
Pleased to see you like it.
For now, the paper is peer-reviewed. So you can choose to cite the cran package "genekitr" as below.


Yunze Liu (2023). genekitr: Gene Analysis Toolkit. R package version 1.1.5. https://cran.r-project.org/web/packages/genekitr/index.html

A BibTeX entry for LaTeX users is

  @Manual{,
    title = {genekitr: Gene Analysis Toolkit},
    author = {Yunze Liu},
    note = {R package version 1.1.5},
    url = {https://cran.r-project.org/web/packages/genekitr/index.html/},
  }

**Comment by maartenciers** [comment]
Thank you!
