### ISSUE TITLE
symbols with Excel misidentified gene names

### ISSUE THREAD

**Issue by MEladawi** [GangLiLab/genekitr#14]
Hi--

I wanted to report that some symbols are official and are not returned by transId().
Also, the tool does not fix the date problem of Excel.

<img width="192" alt="image" src="https://github.com/GangLiLab/genekitr/assets/16545437/ed964d7e-110d-48dc-86da-857d3cf25f24">

**Comment by reedliu** [comment]
Updated the backend data and fixed it.

```
transId(c('GPR75-ASB3','TNFAIP8L2-SCNM1','2-Sep','2-Mar'),c('symbol','entrez'),unique = T)
```
<img width="901" alt="image" src="https://github.com/GangLiLab/genekitr/assets/34302878/30629fab-8a14-4ab8-9804-ac9a8ff2513d">

```
transId(c('GPR75-ASB3','TNFAIP8L2-SCNM1','2-Sep','2-Mar'),c('symbol','entrez'),unique = F)
```
<img width="902" alt="image" src="https://github.com/GangLiLab/genekitr/assets/34302878/efe36ade-9f69-46fd-be4a-e123519cfe8c">
