### ISSUE TITLE
org.db bug in gotangram 

### ISSUE THREAD

**Issue by igumnov-daniel** [GangLiLab/genekitr#2]
Hi!

I'm trying to plot "gotangram" for GO BP enriched _A.thaliana_ data. Other types like bar, upset, and the network worked fine, but gotangram is raising an error: `"Error: Bioconductor orgdb for org.At.eg.db not found. You should install first."`. It looks like a bug since for _A.thaliana_ it's org.At.tair.db 

```
test <- c('AT1G12610', 'AT5G47600', 'AT1G33760') # just to make it easy to reproduce
gs <- getGO(org="Arabidopsis thaliana", ont="bp")
go_bp <- genORA(test,geneset=gs) 
plotEnrich(go_bp, plot_type = "gotangram", sim_method = "Rel", org='Arabidopsis thaliana')
```

_ps_
Many thanks for the package. I do love it.

**Comment by reedliu** [comment]
@igumnov-daniel Thanks for your report. This is a bug in querying At org db. Now please update the tool from GitHub and you would find it works now. :)

```
packageVersion('genekitr')  # 1.0.9
test <- c('AT1G12610', 'AT5G47600', 'AT1G33760') # just to make it easy to reproduce
gs <- getGO(org="Arabidopsis thaliana", ont="bp")
go_bp <- genORA(test,geneset=gs) 
plotEnrich(go_bp, plot_type = "gotangram", sim_method = "Rel", org='Arabidopsis thaliana')
```
<img width="598" alt="image" src="https://user-images.githubusercontent.com/34302878/211455543-4a6bf72c-aea5-4d64-ae52-dd2e057695b4.png">

**Comment by igumnov-daniel** [comment]
Lovely!
Many thanks for the rapid fix 👍🏻
