### ISSUE TITLE
 Could not resolve host: genekitr-china.oss-accelerate.aliyuncs.com

### ISSUE THREAD

**Issue by os306** [GangLiLab/genekitr#21]
Hi, 

When I attempt to run 

"gse <- genGSEA(genelist = ranks, geneset = gs)"

I receive the following error:

"Error in function (type, msg, asError = TRUE)  : 
  Could not resolve host: genekitr-china.oss-accelerate.aliyuncs.com"
  
What is the reason for this error?

**Comment by reedliu** [comment]
Hi, could you provide more information? e.g. which organism are you working on? 
It is better if you could send me your full script and data for testing via Github or email (jieandze1314@gmail.com).

**Comment by reedliu** [comment]
I will close the issue now. If you have any further feedback, please open this issue again.
