### ISSUE TITLE
genInfo missing data

### ISSUE THREAD

**Issue by MEladawi** [GangLiLab/genekitr#23]
Hello, 

I am again having issues with getting genes information. 

for example this gene: ENSG00000257122 has an HGNC symbol but the package reports it as NA.

Best,

**Comment by reedliu** [comment]
Hi, the issue happened because the Ensembl data was updated to the newest version, v110. I have already updated the backend data of genekitr. Please try again.
<img width="1197" alt="image" src="https://github.com/GangLiLab/genekitr/assets/34302878/f5479e43-ff10-43e6-9b1e-00dc045fb068">
