### ISSUE TITLE
Issue with ORA and importCP

### ISSUE THREAD

**Issue by zganjarmia** [GangLiLab/genekitr#24]
Hi,
Firstly, kudos for the development of `genekitr`. It's a great tool and your reasons for its creation resonate so much with my experiences so far.

I'm currently working with the organism _Yarrowia lipolytica_ and have noted some challenges:

1.	The geneset for _Yarrowia lipolytica_ is available in the `geneset` package (GO and KEGG), but there is no organism value attached to it when running getGO:
```R
> mf <- getGO(org = "Yarrowia lipolytica", ont = "mf")
> head(mf$geneset)
          mf          gene
1 GO:0000030 YALI0_C04004g
2 GO:0000030 YALI0_D10549g
3 GO:0000030 YALI0_B01672g
4 GO:0000030 YALI0_E02222g
5 GO:0000030 YALI0_A20922g
6 GO:0000030 YALI0_A13585g
> head(mf$geneset_name)
          id                           name
1 GO:0000030   mannosyltransferase activity
2 GO:0000049                   tRNA binding
3 GO:0000149                  SNARE binding
4 GO:0000166             nucleotide binding
5 GO:0000175 3'-5'-RNA exonuclease activity
6 GO:0000287          magnesium ion binding
> mf$organism
[1] NA
```
2.	However, I ran into issues with follow-up functions, specifically the `genORA` function. It suggests there's no short name for the organism. This is perplexing given the initial inclusion of _Yarrowia lipolytica_ in the geneset. I also tried to add the organism value, but the function still does not work. 
```R
>   gs <- genORA(de.genes$ensembl_gene_id, mf$geneset,padj_method = "BH",
+                p_cutoff = 0.05,)
Error in if (organism == "hg" | organism == "human" | organism == "hsa" |  : 
  argument is of length zero
```

3. I also tried a different route, performing the ORA with ClusterProfiler and then importing the results to `genekitr`. But this too resulted in an error.
```R
>   ora_go <- clusterProfiler::enrichGO(gene = de.genes,
+                         OrgDb = org.Ylipolytica.eg.db,
+                         universe = filtered_data$entrez,
+                         keyType = "ENTREZID",  
+                         ont = "ALL",  # Biological Process
+                         pAdjustMethod = "BH",  # adjust method
+                         pvalueCutoff = 0.05,
+                         minGSSize = 5,
+                         maxGSSize = 500,
+                         readable = FALSE)
>   go_easy <- importCP(ora_go, type = "go")
Error in mapEnsOrg(object@organism) : 
Check the latin_short_name in `genekitr::ensOrg_name`
```
I'd appreciate any insights or suggestions you might have regarding these issues. Is there a workaround or am I possibly missing a step?
Thanks!

**Comment by reedliu** [comment]
Hi, I have fixed the ORA issue and please update packages (`geneset >= 0.2.8` and `genekitr >= 1.2.5` ).
```
# test code
library(geneset)
mf <- getGO(org = "Yarrowia lipolytica", ont = "mf")
mf$organism
# "yarrowia"

library(genekitr)
id <- mf$geneset$gene[1:50]
ora <- genORA(id, mf,padj_method = "BH",p_cutoff = 0.05)
```
<img width="1189" alt="image" src="https://github.com/GangLiLab/genekitr/assets/34302878/0df1b291-f4cb-4a72-b407-e73ec97ac6bb">

Then, you could pass the `ora` result to plot function:
```
# example
plotEnrich(ora, plot_type = "dot")
```
<img width="487" alt="image" src="https://github.com/GangLiLab/genekitr/assets/34302878/1bb0bae7-baad-486b-b641-71ff364f1d48">


For the third question, could you send me the `org.Ylipolytica.eg.db` so I can reproduce and test?

**Comment by reedliu** [comment]
I will close the issue now. If you have any further feedback, please open this issue again.
