### ISSUE TITLE
Problem about transId

### ISSUE THREAD

**Issue by zy-fang** [GangLiLab/genekitr#26]
Hi,

Thank you for your fantastic work and the great convenience you've brought to us.

However, recently, when I attempted to convert a column of IDs, despite setting both the 'keepNA' and 'unique' parameters to TRUE, I noticed that the returned data length doesn't match the input. What's even more peculiar is that when I re-enter the initially missed IDs into the function, the data is then output completely, although some may be None. The package version of genekitr is 1.2.5. Details are as mentioned above. I'm looking forward to your response, and once again, thank you for your awesome work.

![image](https://github.com/GangLiLab/genekitr/assets/47031619/ac82098a-4f79-459d-82b5-83490ae88b21)
![image](https://github.com/GangLiLab/genekitr/assets/47031619/6a2ca33e-b772-4fe4-a99e-72b9ca67045d)

Best wishes,

Zhaoyu

**Comment by reedliu** [comment]
Thanks. Could you please send me an example data of your input IDs so I could test?

**Comment by zy-fang** [comment]
[test.csv](https://github.com/GangLiLab/genekitr/files/13520652/test.csv)
Thanks.

**Comment by reedliu** [comment]
Hi, I have checked the data you uploaded. The reason is that the `test.csv` includes some duplicated ids while `transid` only  gave you the unique result. For example, there are four ids of "TCR".
<img width="319" alt="image" src="https://github.com/GangLiLab/genekitr/assets/34302878/e91d0342-2556-413b-94d7-7d1ce5579170">

**Comment by zy-fang** [comment]
Oh, I got it. Thank you!

**Comment by zy-fang** [comment]
I have another question. I try to convert OR4F5 to Ensembl ID and found that it can be mapped to two different Ensembl IDs. When I checked on https://www.ensembl.org/, I discovered that one of the Ensembl IDs corresponds to another gene symbol. Is this due to different version naming?
![image](https://github.com/GangLiLab/genekitr/assets/47031619/3086089a-b347-4588-82ff-a48d8d20ec82)
![image](https://github.com/GangLiLab/genekitr/assets/47031619/730354a4-f97a-44a7-ac4e-63ab2fd947ee)
![image](https://github.com/GangLiLab/genekitr/assets/47031619/e4ffbed9-8914-406a-87b0-7c695a81101a)

**Comment by reedliu** [comment]
The gene naming framework can be somewhat complicated. Basically, you can understand that "OR4F5" has one official name, which is also "OR4F5". However, it can also be referred to as an alias for other genes, such as "OR4F17" (source: [NCBI Gene](https://www.ncbi.nlm.nih.gov/gene/81099)). This is why Genekitr will also return the ID "ENSG00000176695", which corresponds to "OR4F17".

![image](https://github.com/GangLiLab/genekitr/assets/34302878/c2a5bb9a-c305-4207-a731-ef7031f92670)
