### ISSUE TITLE
Could not resolve host: genekitr-china.oss-accelerate.aliyuncs.com

### ISSUE THREAD

**Issue by chenyangjjj** [GangLiLab/genekitr#27]
Hi reedliu,

I was running the example code, and got the error, "Could not resolve host: genekitr-china.oss-accelerate.aliyuncs.com". It seems like a host issue and data access issue. I am in Europe.

```
data(geneList, package = "genekitr")
entrez_id <- names(geneList)[abs(geneList) > 2]
head(entrez_id, 5)
hg_gs <- geneset::getGO(org = "human",ont = "mf")
```
Best, Chen

**Comment by reedliu** [comment]
Hi, could you first try to download the file via the following link: https://genekitr-china.oss-accelerate.aliyuncs.com/anno/go/mf/human_mf_geneset.fst to check if you can access the data?

**Comment by reedliu** [comment]
I have tested the host and it appears to be normal. If you have any further questions, feel free to contact me.
![image](https://github.com/GangLiLab/genekitr/assets/34302878/142e0a58-d185-4de5-adfc-d4e0629d7505)

**Comment by chenyangjjj** [comment]
Hi, It works well now. Looks like a local network issue. Thanks and nice package!

**Comment by chenyangjjj** [comment]
Hi, It works well now. Looks like a local net issue. Thanks!
