### ISSUE TITLE
transId from alias to symbol no longer works

### ISSUE THREAD

**Issue by stephenrong** [GangLiLab/genekitr#4]
I'm encountering the following error when using transId() to convert gene aliases to symbols despite the same script working a week ago.

Here's the output using the example in the documentation:

```
> transId(c("BCC7", "TP53", "PD1", "PDL1", "TET2"), "sym")
Maybe your "trans_to" argument is wrong, please check again...
Error in tbl_vars_dispatch(x) : object 'res' not found
```

**Comment by reedliu** [comment]
Please use the latest version and test then, thanks.
`library(genekitr)`
`transId(c("BCC7", "TP53", "PD1", "PDL1", "TET2"), "sym")`
`packageVersion('genekitr')`

<img width="628" alt="image" src="https://user-images.githubusercontent.com/34302878/224190695-3c565a63-3f23-4b27-a7d1-510704b40f15.png">
