### ISSUE TITLE
transId loading issue

### ISSUE THREAD

**Issue by MEladawi** [GangLiLab/genekitr#5]
**Describe the bug**
transId not working

**To Reproduce**
Just run the example below.

**Screenshots**
<img width="308" alt="image" src="https://user-images.githubusercontent.com/16545437/225702292-aadc6193-7514-4708-9c37-4f3d202aaf39.png">

**Desktop (please complete the following information):**
 - OS: Windows
 - Version [11 ]
 - Browser [Brave]

**Comment by reedliu** [comment]
Please try loading the package first and then doing `transId()` job.
Similar with the issue #4.
<img width="653" alt="image" src="https://user-images.githubusercontent.com/34302878/225776811-0b40be45-100d-46e7-9f3c-07a96f4ded73.png">

**Comment by reedliu** [comment]
If the issue happens again, please check if there's any dependent packages are not installed.
Please run the code:
`
x <- genInfo(id = c(
  "MCM10", "CDC20", "S100A9", "MMP1", "BCC7",
  "FAKEID", "TP53", "HBD", "NUDT10"
))
`
If this function runs well, you could run `transId` then.

![image](https://user-images.githubusercontent.com/34302878/225779470-dda9ee02-4def-4fcb-8a3e-afbf00088b0d.png)
