### ISSUE TITLE
transId() mouse symbols

### ISSUE THREAD

**Issue by MEladawi** [GangLiLab/genekitr#6]
Hello, 

I was comparing between transId() and biomaRt and found that biomaRt returns more symbols than transId() from ensembl ids. They are official mgi symbols, what would be the reason?

<img width="239" alt="image" src="https://user-images.githubusercontent.com/16545437/225803027-4488ee81-722e-4f4a-a2cd-cb4fa21b6a91.png">

**Comment by reedliu** [comment]
Thanks for your feedback.
The main reason for this issue was that some symbols were omitted during the merge of the backend data. It has been fixed now.
<img width="404" alt="image" src="https://user-images.githubusercontent.com/34302878/226075720-da9f84e5-9d52-43c3-8a10-21e2a3d6df29.png">
