### ISSUE TITLE
transId() updating symbols weird behaviour

### ISSUE THREAD

**Issue by MEladawi** [GangLiLab/genekitr#8]
Hello--

I am updating old gene symbols with keepNA = FALSE, unique = FALSE. 

I am getting some strange data (please see below). 
row 138 (Gm553): is official symbol and it is returned as NA.
row 149-151: the original symbols are Ankrd44 & 4930444A19Rik. 
row 156 & 157 (Mob4): it comes one time as Mob4 and one time as NA.

<img width="182" alt="image" src="https://user-images.githubusercontent.com/16545437/226216961-6e86782e-e6d0-41d7-a0ac-922ac3707aff.png">

**Comment by reedliu** [comment]
The gene name is a little tidious thing.
For example,

- For gene [Gm553 (Mouse Gene, Strain: C3H/HeJ)](https://asia.ensembl.org/mus_musculus_c3hhej/Gene/Summary?g=MGP_C3HHeJ_G0004742&db=core), you could see it is based on strain genomes such as MGP_C3HHeJ and MGP_C57BL6NJ. While the `transId` function now only give results based on standard genome like GRCm39. So does gene Mob4.

- 4930444A19Rik has own records (ENSMUSG00000101674 and 73980 for NCBI, https://www.ncbi.nlm.nih.gov/gene/73980), while it is also the gene alias of Ankrd44 (329154 for NCBI, https://www.ncbi.nlm.nih.gov/gene/329154)

If you want to get one-to-one match, please set "unique=TRUE" and it will return you the best-matching one. (I have given the function some rules to get the best-matching one, while it is a long story...)
