### ISSUE TITLE
transId() does not return all input symbols

### ISSUE THREAD

**Issue by MEladawi** [GangLiLab/genekitr#9]
Hi--

I use transId():

transId(id = IDs, transTo= "symbol", org = "mouse", keepNA = TRUE, unique = TRUE)

which should return all the input symbols; however, it returns less records and there is always a row of all NA.

Please use the same symbols file to verify.

**Comment by reedliu** [comment]
Hi,
It is fixed now. Please update to v1.1.5 then try again. Thanks.
BTW, one ID ("2-Mar") is duplicated in the file so the program only took one.
<img width="917" alt="image" src="https://user-images.githubusercontent.com/34302878/226234652-0d9c349a-8f4b-470e-9bd1-35857e1fc2db.png">
